apiVersion: v1
kind: Service
metadata:
  name: neo4j-lb
spec:
  selector:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: neo4j
    app.kubernetes.io/name: neo4j
  ports:
    - port: 7687
      targetPort: 7687
  type: LoadBalancer